Presentation/Nop.Web/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Primitives;
using Nop.Web.Areas.Admin.Extensions;
using Nop.Web.Areas.Admin.Helpers;
using Nop.Web.Areas.Admin.Infrastructure.Cache;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Discounts;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Tax;
using Nop.Core.Domain.Vendors;
using Nop.Services;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Discounts;
using Nop.Services.ExportImport;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Services.Shipping.Date;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Services.Vendors;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Extensions;
using Nop.Web.Framework.Kendoui;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class ProductController : BaseAdminController
    {
        #region Fields

        private readonly IProductService _productService;
        private readonly IProductTemplateService _productTemplateService;
        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly ICustomerService _customerService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;
        private readonly ILanguageService _languageService;
        private readonly ILocalizationService _localizationService;
        private readonly ILocalizedEntityService _localizedEntityService;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IPictureService _pictureService;
        private readonly ITaxCategoryService _taxCategoryService;
        private readonly IProductTagService _productTagService;
        private readonly ICopyProductService _copyProductService;
        private readonly IPdfService _pdfService;
        private readonly IExportManager _exportManager;
        private readonly IImportManager _importManager;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IPermissionService _permissionService;
        private readonly IAclService _aclService;
        private readonly IStoreService _storeService;
        private readonly IOrderService _orderService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IVendorService _vendorService;
        private readonly IDateRangeService _dateRangeService;
        private readonly IShippingService _shippingService;
        private readonly IShipmentService _shipmentService;
        private readonly ICurrencyService _currencyService;
        private readonly CurrencySettings _currencySettings;
        private readonly IMeasureService _measureService;
        private readonly MeasureSettings _measureSettings;
        private readonly IStaticCacheManager _cacheManager;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IDiscountService _discountService;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
        private readonly IShoppingCartService _shoppingCartService;
        private readonly IProductAttributeFormatter _productAttributeFormatter;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IDownloadService _downloadService;
        private readonly ISettingService _settingService;
        private readonly TaxSettings _taxSettings;
        private readonly VendorSettings _vendorSettings;

        #endregion

        #region Ctor

        public ProductController(IProductService productService,
            IProductTemplateService productTemplateService,
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            ICustomerService customerService,
            IUrlRecordService urlRecordService,
            IWorkContext workContext,
            ILanguageService languageService,
            ILocalizationService localizationService,
            ILocalizedEntityService localizedEntityService,
            ISpecificationAttributeService specificationAttributeService,
            IPictureService pictureService,
            ITaxCategoryService taxCategoryService,
            IProductTagService productTagService,
            ICopyProductService copyProductService,
            IPdfService pdfService,
            IExportManager exportManager,
            IImportManager importManager,
            ICustomerActivityService customerActivityService,
            IPermissionService permissionService,
            IAclService aclService,
            IStoreService storeService,
            IOrderService orderService,
            IStoreMappingService storeMappingService,
            IVendorService vendorService,
            IDateRangeService dateRangeService,
            IShippingService shippingService,
            IShipmentService shipmentService,
            ICurrencyService currencyService,
            CurrencySettings currencySettings,
            IMeasureService measureService,
            MeasureSettings measureSettings,
            IStaticCacheManager cacheManager,
            IDateTimeHelper dateTimeHelper,
            IDiscountService discountService,
            IProductAttributeService productAttributeService,
            IBackInStockSubscriptionService backInStockSubscriptionService,
            IShoppingCartService shoppingCartService,
            IProductAttributeFormatter productAttributeFormatter,
            IProductAttributeParser productAttributeParser,
            IDownloadService downloadService,
            ISettingService settingService,
            TaxSettings taxSettings,
            VendorSettings vendorSettings)
        {
            this._productService = productService;
            this._productTemplateService = productTemplateService;
            this._categoryService = categoryService;
            this._manufacturerService = manufacturerService;
            this._customerService = customerService;
            this._urlRecordService = urlRecordService;
            this._workContext = workContext;
            this._languageService = languageService;
            this._localizationService = localizationService;
            this._localizedEntityService = localizedEntityService;
            this._specificationAttributeService = specificationAttributeService;
            this._pictureService = pictureService;
            this._taxCategoryService = taxCategoryService;
            this._productTagService = productTagService;
            this._copyProductService = copyProductService;
            this._pdfService = pdfService;
            this._exportManager = exportManager;
            this._importManager = importManager;
            this._customerActivityService = customerActivityService;
            this._permissionService = permissionService;
            this._aclService = aclService;
            this._storeService = storeService;
            this._orderService = orderService;
            this._storeMappingService = storeMappingService;
            this._vendorService = vendorService;
            this._dateRangeService = dateRangeService;
            this._shippingService = shippingService;
            this._shipmentService = shipmentService;
            this._currencyService = currencyService;
            this._currencySettings = currencySettings;
            this._measureService = measureService;
            this._measureSettings = measureSettings;
            this._cacheManager = cacheManager;
            this._dateTimeHelper = dateTimeHelper;
            this._discountService = discountService;
            this._productAttributeService = productAttributeService;
            this._backInStockSubscriptionService = backInStockSubscriptionService;
            this._shoppingCartService = shoppingCartService;
            this._productAttributeFormatter = productAttributeFormatter;
            this._productAttributeParser = productAttributeParser;
            this._downloadService = downloadService;
            this._settingService = settingService;
            this._taxSettings = taxSettings;
            this._vendorSettings = vendorSettings;
        }

        #endregion

        #region Utilities

        protected virtual void UpdateLocales(Product product, ProductModel model)
        {
            foreach (var localized in model.Locales)
            {
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.Name,
                    localized.Name,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.ShortDescription,
                    localized.ShortDescription,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,
                    x => x.FullDescription,
                    localized.FullDescription,
                    localized.LanguageId);
                _localizedEntityService.SaveLocalizedValue(product,

Presentation/Nop.Web/Areas/Admin/Views/Product/AddAttributeCombinationPopup.cshtml
@using Microsoft.AspNetCore.Routing
@model AddProductAttributeCombinationModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Admin.Catalog.Products.ProductAttributes.AttributeCombinations.AddTitle").Text;
}

@if (ViewBag.RefreshPage == true)
{
    <script type="text/javascript">
        try {window.opener.document.forms['@(Context.Request.Query["formId"])'].@(Context.Request.Query["btnId"]).click();}
        catch (e){}
        window.close();
    </script>
}

<form asp-controller="Product" asp-action="AddAttributeCombinationPopup"
      asp-route-productId="@Context.Request.Query["productId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.ProductAttributes.AttributeCombinations.AddTitle")
        </h1>
        <div class="pull-right">
            &nbsp;
        </div>
    </div>
    <div class="content">
        @if (Model.Warnings.Count > 0)
        {
            <div class="callout callout-danger">
                <ul>
                    @foreach (var warning in Model.Warnings)
                    {
                        <li>@warning</li>
                    }
                </ul>
            </div>
        }

        <div asp-validation-summary="All"></div>
        <div class="form-horizontal">
            <div class="panel-group">
                <div class="panel panel-default panel-popup">
                    <div class="panel-body">
                        @await Html.PartialAsync("_ProductAttributes", Model.ProductAttributes)
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="StockQuantity"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="StockQuantity"/>
                                <span asp-validation-for="StockQuantity"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="AllowOutOfStockOrders"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="AllowOutOfStockOrders"/>
                                <span asp-validation-for="AllowOutOfStockOrders"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="Sku"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="Sku"/>
                                <span asp-validation-for="Sku"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="ManufacturerPartNumber"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="ManufacturerPartNumber"/>
                                <span asp-validation-for="ManufacturerPartNumber"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="Gtin"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="Gtin"/>
                                <span asp-validation-for="Gtin"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="OverriddenPrice"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="OverriddenPrice"/>
                                <span asp-validation-for="OverriddenPrice"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <nop-label asp-for="NotifyAdminForQuantityBelow"/>
                            </div>
                            <div class="col-sm-8">
                                <nop-editor asp-for="NotifyAdminForQuantityBelow"/>
                                <span asp-validation-for="NotifyAdminForQuantityBelow"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-8 col-sm-offset-4">
                                <button type="submit" id="add-attribute-combination" name="add-attribute-combination" class="btn btn-primary">
                                    @T("Admin.Catalog.Products.ProductAttributes.AttributeCombinations.AddNew")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/Edit.cshtml
@model ProductModel

@{
    //page title
    ViewBag.Title = T("Admin.Catalog.Products.EditProductDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="Edit" method="post" id="product-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.EditProductDetails") - @Model.Name
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.Products.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="button" onclick="javascript:OpenWindow('@Url.RouteUrl("Product", new {SeName = Model.SeName})', 800, 600, true); return false;" class="btn bg-purple">
                <i class="fa fa-eye"></i>
                @T("Admin.Common.Preview")
            </button>
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <button type="button" name="copyproduct" class="btn bg-olive" data-toggle="modal" data-target="#copyproduct-window">
                <i class="fa fa-clone"></i>
                @T("Admin.Catalog.Products.Copy")
            </button>
            <span id="product-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_details_buttons", additionalData = Model.Id })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="product-delete" />

@if (!Model.IsLoggedInAsVendor)
{
    //product editor settings modal
    @await Html.PartialAsync("_ProductEditorSettingsModal", Model)
}

@*copy product form*@
<div id="copyproduct-window" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="copyproduct-window-title">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="copyproduct-window-title">@T("Admin.Catalog.Products.Copy")</h4>
            </div>
            <form asp-controller="Product" asp-action="CopyProduct" method="post">
                <div class="form-horizontal">
                    <div class="modal-body">
                        <input asp-for="CopyProductModel.Id" type="hidden" />
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Name" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Name" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.Published" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.Published" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4">
                                <nop-label asp-for="CopyProductModel.CopyImages" />
                            </div>
                            <div class="col-md-8">
                                <nop-editor asp-for="CopyProductModel.CopyImages" />
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">
                            @T("Admin.Catalog.Products.Copy")
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeMappingEdit.cshtml
@model ProductModel.ProductAttributeMappingModel

@{
    //page title
    ViewBag.Title = T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Products");
}

<form asp-controller="Product" asp-action="ProductAttributeMappingEdit" method="post" id="productattribute-form">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.EditAttributeDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="Edit" asp-route-id="@Model.ProductId">@T("Admin.Catalog.Products.ProductAttributes.Attributes.BackToProduct")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="productattribute-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_attribute_mapping_details_buttons", additionalData = Model.Id })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeMapping", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-action="ProductAttributeMappingDelete" asp-button-id="productattribute-delete" />

Presentation/Nop.Web/Areas/Admin/Views/Product/ProductAttributeValueCreatePopup.cshtml
@model ProductModel.ProductAttributeValueModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew").Text;
}
<form asp-controller="Product" asp-action="ProductAttributeValueCreatePopup"
      asp-route-productAttributeMappingId="@Context.Request.Query["productAttributeMappingId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.ProductAttributes.Attributes.Values.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_attribute_value_details_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateProductAttributeValue", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/TierPriceCreatePopup.cshtml
@model ProductModel.TierPriceModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Admin.Catalog.Products.TierPrices.AddNew").Text;
}

<form asp-controller="Product" asp-action="TierPriceCreatePopup"
      asp-route-productId="@Context.Request.Query["productId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.TierPrices.AddNew")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_tier_price_details_buttons" })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateTierPrice", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/TierPriceEditPopup.cshtml
@model ProductModel.TierPriceModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Admin.Catalog.Products.TierPrices.Edit").Text;
}

<form asp-controller="Product" asp-action="TierPriceEditPopup"
      asp-route-btnId="@Context.Request.Query["btnId"]"
      asp-route-formId="@Context.Request.Query["formId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Products.TierPrices.Edit")
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_tier_price_details_buttons", additionalData = Model.Id })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdateTierPrice", Model)
</form>

Presentation/Nop.Web/Areas/Admin/Views/Product/_CreateOrUpdate._StockQuantityHistory.cshtml
@model ProductModel
@inject AdminAreaSettings adminAreaSettings

@{
    var defaultGridPageSize = adminAreaSettings.DefaultGridPageSize;
    var gridPageSizes = adminAreaSettings.GridPageSizes;
}

<div class="panel-group">
    <p>
        @T("Admin.Catalog.Products.StockQuantityHistory.Hint")
    </p>
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_details_stock_quantity_history_top", additionalData = Model.Id })
    @*hide the entire search block if no elements are displayed*@
    <div class="panel panel-default panel-search" @(Model.AvailableWarehouses.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group" @(Model.AvailableWarehouses.SelectionIsNotPossible() ? Html.Raw("style=\"display:none\"") : null)>
                        <div class="col-md-4">
                            <nop-label asp-for="StockQuantityHistory.SearchWarehouseId" />
                        </div>
                        <div class="col-md-8">
                            <nop-select asp-for="StockQuantityHistory.SearchWarehouseId" asp-items="Model.AvailableWarehouses" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-8 col-md-offset-4">
                            <button type="button" id="search-stock-quantity-history" class="btn btn-primary btn-search">
                                <i class="fa fa-search"></i>
                                @T("Admin.Common.Search")
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <div id="stock-quantity-history-grid"></div>

            <script type="text/javascript">
                $(document).ready(function() {
                    $("#stock-quantity-history-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("StockQuantityHistory", "Product"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: additionalData
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function(e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            pageSize: @(defaultGridPageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            pageSizes: [@(gridPageSizes)],
                            @await Html.PartialAsync("_GridPagerMessages")
                        },
                        scrollable: false,
                        columns: [
                            {
                                field: "WarehouseName",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.Warehouse")",
                                width: 200
                            }, {
                                field: "AttributeCombination",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.Combination")",
                                width: 220,
                                encoded: false
                            }, {
                                field: "QuantityAdjustment",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.QuantityAdjustment")",
                                width: 150,
                                template: '# if(QuantityAdjustment > 0) { # +#=QuantityAdjustment# # } else { # #=QuantityAdjustment# # } #'
                            }, {
                                field: "StockQuantity",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.StockQuantity")",
                                width: 130
                            }, {
                                field: "Message",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.Message")"
                            }, {
                                field: "CreatedOn",
                                title: "@T("Admin.Catalog.Products.StockQuantityHistory.Fields.CreatedOn")",
                                type: "date",
                                format: "{0:G}",
                                width: 170
                            }
                        ]
                    });
                });
            </script>

            <script type="text/javascript">
                $(document).ready(function() {
                    $('#search-stock-quantity-history').click(function() {
                        $('#stock-quantity-history-grid').data('kendoGrid').dataSource.page(1);
                        return false;
                    });
                });

                function additionalData() {
                    var data = {
                        productId: @Model.Id,
                        warehouseId: $('#@Html.IdFor(model => model.StockQuantityHistory.SearchWarehouseId)').val()
                    };
                    addAntiForgeryToken(data);
                    return data;
                }
            </script>
        </div>
    </div>
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = "admin_product_details_stock_quantity_history_bottom", additionalData = Model.Id })
</div>